### PR TITLE
Fixed xp/level and double recycling of pokeballs, potions and revives.

### PR DESCRIPTION
**Pull request by Nimryel**
Keep in mind the master branch is unstable due to the dumper change, specifically 3260ae6acb48de606bd940ab5e7854d39afe56f1 - it causes an error when running the bot.

### CODE REVIEW

**Comment by DurtyFree** [comment]
Can somebody pls verify this?

**Comment by DeadElle** [comment]
confirmed working

**Comment by DurtyFree** [comment]
@Nimryel Can you pls fix the conflicts? Weird stuff going on there.

@DeadElle Thx

**Comment by Nimryel** [comment]
@DeadElle Will re-create.

**Pull request closed without merging**
