### PR TITLE
IV Rounding and LuckyEgg

### PR DESCRIPTION
**Pull request by NinjaKemuri**
Changed the rounding for CatchPokemonTask on IV.
Recovered previous "not enough pokemon" message for using lucky egg while evolving.

### CODE REVIEW

**Comment by ShallowHacker** [comment]
In release update notes it says :
[Farm all Pokemon in neighbourhood]
 [Search for gyms/pokestops/spawns]

Can anyone tell em what these mean or how to use them since sniping isnt working?
Would be nice to have it hit gyms, auto potion/revive, take gyms and put in say, 5th best pokemon, or something after it beats the gym. I don't see the purpose of search for gyms if it doesn't do anything. and for the spawns, i'm not sure what that means either..

**Comment by ShallowHacker** [comment]
Yeah, 2 things. Didn't answer my question and decided to be a dick about it.
Cool. Shows what kind of person you are.

**Comment by hakkotsu** [comment]
You have posted complete irrelevant question in pull request and expect to get an answer? Go back to reddit or discord.

**Comment by ShallowHacker** [comment]
I don't know how to use the issues button or anything. Maybe if you guys
were more informative about it.. add it to the damn readme. "For issues
visit.." how hard would that be.. aren't you a coder? Fking aye. You don't
have to be a dick just because someone messed up.

**Comment by l3uddz** [comment]
Dont worry, your not the first to mess up and won't be the last.

**Comment by DurtyFree** [comment]
@NinjaKemuri Please add the added messages to the translations

**Comment by DurtyFree** [comment]
Looks fine, thx @NinjaKemuri

**Pull request merged**
