### PR TITLE
Humanize ball throwing

### PR DESCRIPTION
**Pull request by eslindsey**
This addresses #28: Bot only performs perfect throws, which is suspicious

`ThrowAccuracyMin` and `ThrowAccuracyMax` range is 0.0-1.0 (converted later to 0.1-1.95 for `normalizedRecticleSize`)
`ThrowSpinFrequency` range is 0.0-1.0 and corresponds to how often you want to throw curve balls (which sets `spinModifier` to 1.0 instead of 0.0)

Defaults maintain current functionality:
`ThrowAccuracyMin` = 1.0
`ThrowAccuracyMax` = 1.0
`ThrowSpinFrequency` = 1.0

### CODE REVIEW

**Comment by Tobiti** [comment]
Please add a variable to activate and activate it

**Comment by Tobiti** [comment]
*deactivate

**Comment by eslindsey** [comment]
The default options duplicate current functionality, "deactivating" it.

**Comment by DurtyFree** [comment]
Please fix the conflicts and add a setting to enable / disable it @eslindsey

**Comment by DeadElle** [comment]
@eslindsey pls do a better merge keeping the current Settings.cs format

**Comment by DurtyFree** [comment]
@eslindsey Please consider @DeadElle commit

**Comment by DurtyFree** [comment]
Seems good, good work  :) @eslindsey

**Comment by Emuuung** [comment]
Add this to wiki because it's hard to find out in config file if `100.0` or `1.0` is equal to 100%

**Pull request merged**
