### PR TITLE
Fix .csv delimiter

### PR DESCRIPTION
**Pull request by Alintya**
Fixes this shit
http://i.imgur.com/AJGerMR.png

### CODE REVIEW

**Comment by cabbscripts** [comment]
works fine as is?

(win7 ms excel)
wat

**Comment by Alintya** [comment]
Impossibru, I've been creating csv files before always using ";"
can you post some content of the original file?

**Comment by cabbscripts** [comment]
Name,Level,CP,IV,Move1,Move2
Magikarp,03,19,100.00%,SplashFast,Struggle
Eevee,13,398,98.38%,TackleFast,Swift
Magikarp,20,141,97.59%,SplashFast,Struggle

**Comment by Alintya** [comment]
seems legit

**Comment by cabbscripts** [comment]
Maybe a localization issue?

Edit: found the likely culprit, also csv does stand for comma-separated
derp

**Comment by Alintya** [comment]
you appear to be right

**Comment by Alintya** [comment]
Should look for a way to read that windows setiing i guess

**Pull request closed without merging**
