### PR TITLE
[Feature] Added Moveset Rankings

### PR DESCRIPTION
**Pull request by marksterxxx**
-Added File PokemonMoveInfo.cs
-Rankings are based on this excel file
https://docs.google.com/spreadsheets/d/1I0Kt_QblThH2rf7vdZOC2L1Nuf7Y1xx68j_KYwfcpXc/edit#gid=413785499

### CODE REVIEW

**Comment by marksterxxx** [comment]
ex

**Comment by DurtyFree** [comment]
Seems good, thanks!:)

**Comment by eslindsey** [comment]
Does this account for the STA bonus discussed by @Fenixxia since it deals with the movesets?

**Comment by moredhel92** [comment]
low avg is better or worse?

**Comment by eslindsey** [comment]
@moredhel92 higher number is better.

**Pull request merged**
