### PR TITLE
Pokemon name translation

### PR DESCRIPTION
**Pull request by Earisu**
These translate the pokemon name on the **console output**, **dumped csv files** and **the rename function** too.

**This is NOT so you can use localized pokemon name on config files**

### CODE REVIEW

**Comment by Emuuung** [comment]
OMG, I thought names of pokemon were the same everywhere (except in japanese which is the original language). Here in South America Pokemon's names are the same in english.

**Comment by Kalashnikitty** [comment]
Here are some translations: http://pokewiki.de/Pok%C3%A9mon-Liste

**Comment by MadEyez** [comment]
Sorry, I don't know how to change the files (or maybe I don't have the right to do so).
Here ist the missing text for the German translation:
"Missingno",
"Bisasam",
"Bisaknosp",
"Bisaflor",
"Glumanda",
"Glutexo",
"Glurak",
"Schiggy",
"Schillok",
"Turtok",
"Raupy",
"Safcon",
"Smettbo",
"Hornliu",
"Kokuna",
"Bibor",
"Taubsi",
"Tauboga",
"Tauboss",
"Rattfratz",
"Rattikarl",
"Habitak",
"Ibitak",
"Rettan",
"Arbok",
"Pikachu",
"Raichu",
"Sandan",
"Sandamer",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Piepi",
"Pixi",
"Vulpix",
"Vulnona",
"Pummeluff",
"Knuddeluff",
"Zubat",
"Golbat",
"Myrapla",
"Duflor",
"Giflor",
"Paras",
"Parasek",
"Bluzuk",
"Omot",
"Digda",
"Digdri",
"Mauzi",
"Snobilikat",
"Enton",
"Entoron",
"Menki",
"Rasaff",
"Fukano",
"Arkani",
"Quapsel",
"Quaputzi",
"Quappo",
"Abra",
"Kadabra",
"Simsala",
"Machollo",
"Maschock",
"Machomei",
"Knofensa",
"Ultrigaria",
"Sarzenia",
"Tentacha",
"Tentoxa",
"Kleinstein",
"Georok",
"Geowaz",
"Ponita",
"Gallopa",
"Flegmon",
"Lahmus",
"Magnetilo",
"Magneton",
"Porenta",
"Dodu",
"Dodri",
"Jurob",
"Jugong",
"Sleima",
"Sleimok",
"Muschas",
"Austos",
"Nebulak",
"Alpollo",
"Gengar",
"Onix",
"Traumato",
"Hypno",
"Krabby",
"Kingler",
"Voltobal",
"Lektrobal",
"Owei",
"Kokowei",
"Tragosso",
"Knogga",
"Kicklee",
"Nockchan",
"Schlurp",
"Smogon",
"Smogmog",
"Rihorn",
"Rizeros",
"Chaneira",
"Tangela",
"Kangama",
"Seeper",
"Seemon",
"Goldini",
"Golking",
"Sterndu",
"Starmie",
"Pantimos",
"Sichlor",
"Rossana",
"Elektek",
"Magmar",
"Pinsir",
"Tauros",
"Karpador",
"Garados",
"Lapras",
"Ditto",
"Evoli",
"Aquana",
"Blitza",
"Flamara",
"Porygon",
"Amonitas",
"Amoroso",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Relaxo",
"Arktos",
"Zapdos",
"Lavados",
"Dratini",
"Dragonir",
"Dragoran",
"Mewtu",
"Mew"

**Comment by DurtyFree** [comment]
This doesnt make any sense as long as you dont implement proper loading of the translations for the pokemon names.
Please implement that @Earisu

**Comment by Earisu** [comment]
@DurtyFree Yes the names are loaded from the translation file and then used in the code. You can search for GetPokemonName() references to check where it's used.

**Comment by DurtyFree** [comment]
You should consider using a Dictionary / Key pairs for the pokemon names. This solutions is at the moment dependant on the right order of the names in the list.

This can be kinda confusing and might provoke user errors on translating pokemon names.

**Comment by Earisu** [comment]
@DurtyFree  Done :).

**Comment by DurtyFree** [comment]
@Earisu Lets change the actual keys ( Pokemon Ids ) to be the english pokemon name instead of the id, this makes it cleaner. Thx!:)

**Comment by Earisu** [comment]
@DurtyFree I saw that you merged the PR, did you still want to change the keys to the english pokemon names ?

**Comment by DurtyFree** [comment]
@Earisu Already did that myself:)

**Pull request merged**
