### PR TITLE
Pokestop coords

### PR DESCRIPTION
**Pull request by l3uddz**
Pokestop console messages now display their coords.

### CODE REVIEW

**Comment by maartenpeels** [comment]
I don't like this, maybe make it an option like; "ShowMoreInfoInChat" and add extra info on allot of stuff

**Comment by FatSacks** [comment]
I would like the option to see the coords and/or to show the last coords at logout reflected in the log

**Comment by l3uddz** [comment]
I find it very useful to be able to copy cords of last poke stop, stop bot and start nox up at the same coords.

**Comment by DurtyFree** [comment]
You should implement a proper feature for saving the last visited pokestop and bring the trainer back to that coord on restart / startup.

We shouldn't get the console output too messy.

**Pull request closed without merging**
