### PR TITLE
All pokemons above 300 will be used with greatball no matter what u s…

### PR DESCRIPTION
**Pull request by chriszhangz**
All pokemons above 300 will be caught with great ball no matter what u set "UseGreatBallAboveCp".

### CODE REVIEW

**Comment by vfuyong** [comment]
This is a known issue...and I think the decision to use what ball should be based on probability, not CP.

**Comment by chriszhangz** [comment]
@vfuyong I think most people like me don't want bot to waste great balls on common pokemon with high cp and low catch probability like pidgey.  So It should make a setting like "UseGreatBallAboveCp" ont only based on probability.

**Comment by Zenithxm** [comment]
i'm agree with @chriszhangz, i don't want to waste greatball for kabuto with cp 800 and change 22%, better its flee use 1 - 6 pokeball than success use 3 greatball. (but i will happy if only use 1 pokeball LOL)

thanks for your work

**Comment by DurtyFree** [comment]
Got already fixed.

**Pull request closed without merging**
