### PR TITLE
PR back from Necro days to have events for the GUI

### PR DESCRIPTION
**Pull request by nicoschmitt**

### CODE REVIEW

**Comment by IniTW8X** [comment]
This please :)

**Comment by mich3lam** [comment]
@DurtyFree @nicoschmitt the changes in "CatchPokemonTask.cs" makes the console spam error sometimes when trying to catch pokemons

**Comment by nicoschmitt** [comment]
do you have a screenshot or log?

**Comment by nicoschmitt** [comment]
ok. not sure why this happend as I can't reproduce it, but that should fix it : https://github.com/PocketMobsters/PokeMobBot/pull/71

**Pull request merged**
