### PR TITLE
Do not catch pokemon

### PR DESCRIPTION
**Pull request by ghost**
Defaulted to false, so that people don't go ape shit.

### CODE REVIEW

**Comment by Jazed** [comment]
Have you build and tested this?

**Comment by icicleplayer** [comment]
Could you include DoNotCatchPokemonBelowIV: ?

**Comment by DurtyFree** [comment]
Do we really need this? This PR also includes many more changes, please fix or re PR it

**Comment by jabberjabber** [comment]
Looks like https://github.com/PocketMobsters/PokeMobBot/pull/298

**Pull request closed without merging**
