### PR TITLE
Checking for incorrect percentage values in config, added optional automatic inventory management, additional inventory and Pokemon stats in console.

### PR DESCRIPTION
**Pull request by Nimryel**

### CODE REVIEW

**Comment by BradlySharpe** [comment]
Still tries to use higher tier balls even if you have none. Needs brackets around the OR, alternatively use an AND as in #493

**Comment by Nimryel** [comment]
Should have been in the initial commit but got lost when I merged with my testing branch. Fixed now.

**Comment by DurtyFree** [comment]
Nice, please fix the outstanding conflicts:) @Nimryel

**Comment by Nimryel** [comment]
@DurtyFree Done.

**Comment by Nimryel** [comment]
Also added optional automatic inventory management which keeps the best items and discards the weakest when above set max.

**Comment by Nimryel** [comment]
Added the rest of the items to the log, as well as item and Pokemon totals. Useful for seeing if inventory is getting clogged and what's to blame.

**Comment by bjornegrim** [comment]
merge gogogo

**Comment by DurtyFree** [comment]
Well done, will merge

**Comment by jabberjabber** [comment]
I think AutomaticInventoryManagement  should default to true.

**Comment by bin101** [comment]
Please revert this, if an item limit is reached, it will discard all items of this type not only the weakest.

**Pull request merged**
