### PR TITLE
Fixed no pokestop within range

### PR DESCRIPTION
**Pull request by ghost**
FarmPokestopsGPXTask.cs has there own GetPokeStops(), so it is useless to only look for pokestops withing 40m when a user defined a larger radius. While keeping the 40m in the FarmPokeStopsGPXTask.cs

### CODE REVIEW

**Comment by littlemonster1** [comment]
@mvegter197 the original idea as far as I can see was to check if lootable Pokestops are nearby when walking along the paths. That might not work properly idk.

It is testing a radius of 40m of the current location, which means the distance to ensure the pokestop can be looted. It is disconnected from the distance from the starting locatiion.

But MaxTravelDistanceInMeters is only used when not using GPX, hence walking around from a starting location and I think it is used during Teleportation as well, as far as I can see.

I do not think it makes sense to use it here since that would mean the user has to adjust it so that all points on the given route are within the MaxTravelDistanceInMeters (which is kind of pointless).

I do not think MaxTravelDistanceInMeters should be used at all while GPX Pathing.

**Comment by ghost** [comment]
@littlemonster1 After I read my first comment, it seems a bit confusing. I left the FarmPokestopsGPXTask as it was, so it will only look within 40m. I changed the regular FarmPokestops as that was limited to 40m while we did define the MaxTravleDistanceInMeters.

TL:DR:
FarmPokestops limited to user defined MaxTravelDistance
FarmPokestopsGPXTask limited to 40m to prevent going to far from the defined path.

**Comment by littlemonster1** [comment]
@mvegter197 still not exactly sure about your reasoning to change it in this particular file

UseNearbyPokestopsTask is only called during GPX Pathing, not during normal PokestopFarming.

The Normal Pokestop Farming procedure is defined within the FarmPokestop.cs

I am not sure why but there is also a comment in GPX Pathing saying the GPX Pathing Pokestop function is never used due to the calling and functions of UseNearbyPokestopsTask. Therefore, if that is true UseNearbyPokestopsTask is the only PokeStop function for GPX Pathing. I can confirm that it worked for GPX pathing with 40m, but I was in range. So not sure about possible errors.

**Comment by ghost** [comment]
@littlemonster1 Seems like I have been changing stuff in the wrong file. Thanks for pointing it out.

**Pull request closed without merging**
