### PR TITLE
Xp on catch

### PR DESCRIPTION
**Pull request by LNSDISCORDER**
outputs xp on catch line

### CODE REVIEW

**Comment by DurtyFree** [comment]
Do we really need this? @LNSDISCORDER

**Comment by LNSDISCORDER** [comment]
Its not a priority, just a QOL for people. Besides, i was just playing with the web pr while i was out, sorry to waste your time.

**Comment by DurtyFree** [comment]
People shall just tell ( comment ) wether they want this or not, and you dont waste my time. We appreciate every contribution:)

**Comment by littlemonster1** [comment]
I think it would be nice since I sometimes read the output and since we have humanizing functions for throwing this might actually differ. If we would not have it, there would not really be a point since the xp gain is static for each action.

**Comment by mennas** [comment]
Would be nice if we could know how much xp we get on catching pokemon

**Comment by GeertHauwaerts** [comment]
That's a great QOL!

**Comment by Fenixxia** [comment]
As far as I know. With the latest update, no additional experience when catching pokemon is no longer given. For any successful shots pokeball.

Not 100% information.

**Comment by pokepleb** [comment]
@Fenixxia this could be due to spaghetti code since no changelog on the removal was given, might come back on the next update along with minor text fixes

**Comment by littlemonster1** [comment]
I think it still works it just not displayed anymore in game but most catches still award 200 xp, hence 100 for the catch and 100 for the perfect throw.

**Comment by mush35** [comment]
nice idea.

**Comment by DurtyFree** [comment]
Lets just try gettin this in and see what happens;)

**Pull request merged**
